### ISSUE TITLE
Fix Social Media Logo Spacing

### ISSUE THREAD

**Issue by ldt116** [polaris-infosec/polarisec.com#1]
![image](https://user-images.githubusercontent.com/2363783/144014869-218c31cd-a40c-4a2c-a71b-5ae181333c08.png)

On Google Chrome browser, the spacing is not good. 
Please align more space at the bottom of the logo.

Note: this is ok on Firefox

**Comment by nhatthien0812** [comment]
> ![image](https://user-images.githubusercontent.com/2363783/144014869-218c31cd-a40c-4a2c-a71b-5ae181333c08.png)
> 
> On Google Chrome browser, the spacing is not good. Please align more space at the bottom of the logo.
> 
> Note: this is ok on Firefox

Fixed

**Comment by ldt116** [comment]
OK
