### ISSUE TITLE
Edit the Company page

### ISSUE THREAD

**Issue by ttnguyen13** [polaris-infosec/polarisec.com#5]
Remove the first sentence about being founded in 2019. Remove the last line. Only keep the line about "Enabling..."

Change About Us to Mission.

**Comment by nhatthien0812** [comment]
> Remove the first sentence about being founded in 2019. Remove the last line. Only keep the line about "Enabling..."
> 
> Change About Us to Mission.

Done

**Comment by ttnguyen13** [comment]
forgot to remove the last line "Learn more..."

we only need the one line, "Enabling..." and change About Us to Mission

**Comment by ttnguyen13** [comment]
also please center Vinh's profile since it looks weird with him just on the left with a blank spot on the right. Thanks, Thien.
