### ISSUE TITLE
Add Blog + Twitter link into the footer

### ISSUE THREAD

**Issue by ldt116** [polaris-infosec/polarisec.com#6]
- [ ] Add the blog link to the footer, next to the Facebook 

![image](https://user-images.githubusercontent.com/2363783/145666743-8706bcfb-6a0f-470f-b1a4-4caf41d55e6e.png)

**Comment by nhatthien0812** [comment]
![image](https://user-images.githubusercontent.com/67832021/145747584-000c6711-7427-432d-9d34-401431b89d13.png)
Done

**Comment by ldt116** [comment]
Which icon is that

> ![image](https://user-images.githubusercontent.com/67832021/145747584-000c6711-7427-432d-9d34-401431b89d13.png) Done

Please add the Medium logo.

Update task:
- [x] Add Twitter link also. 

Order is: Linkedin - Facebook - Twitter - Medium 
Link: https://twitter.com/polarisinfosec/

**Comment by nhatthien0812** [comment]
> Which icon is that
> 
> > ![image](https://user-images.githubusercontent.com/67832021/145747584-000c6711-7427-432d-9d34-401431b89d13.png) Done
> 
> Please add the Medium logo.
> 
> Update task:
> 
> * [x]  Add Twitter link also.
> 
> Order is: Linkedin - Facebook - Twitter - Medium Link: https://twitter.com/polarisinfosec/

![image](https://user-images.githubusercontent.com/67832021/145770117-b8a2d14b-9616-4a85-9cbb-c8d6871a65d0.png)
Done

**Comment by ldt116** [comment]
Cái logo của Medium vẫn sai. Em kiểm tra trang Medium để lấy logo đúng chứ cứ lấy bừa hoài vậy
